name: first

on: push # on multiple events --> on: [push, pull_request]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'Get-ChildItem Env: | Sort-Object name'
