name: first

on: push # on multiple events --> on: [push, pull_request]

jobs:
  job1:
    name: First job
    run-on: ubuntu-latest
    - name: Step one
     uses: actions/checkout@v3
    - name: Step two
    run: env | sort

  job2:
    name: Second job
    run-on: windows-latest
    -name: Step one
     uses: actions/checkout@v3
    -name: Step two
    run: "Get-ChildItem Env: | Sort-Object name"

    