name: first

on: push # on multiple events --> on: [push, pull_request]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      run: env | sort

  second-job:
    runs-on: windows-latest
    steps:
      uses: actions/checkout@v3
      run: 'Get-ChildItem Env: | Sort-Object name'
