name: first

on: push # on multiple events --> on: [push, pull_request]

jobs:
  job_1:
    name: First job
    runs-on: ubuntu-latest
    - name: Step one
     uses: actions/checkout@v3
    - name: Step two
    run: env | sort

  job_2:
    name: Second job
    runs-on: windows-latest
    -name: Step one
     uses: actions/checkout@v3
    -name: Step two
    run: "Get-ChildItem Env: | Sort-Object name"

    